services:
  - type: web
    name: excel-cleaner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
